import { precacheAndRoute } from 'workbox-precaching';

declare const self: any;

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for Web Push events in background
self.addEventListener('push', (event: any) => {
  try {
    const data = event.data ? event.data.json() : {};
    const title = data.title || '縁側';
    const options: any = {
      body: data.body || '新しいやり取りがあります。',
      icon: 'favicon.svg',
      badge: 'favicon.svg',
      vibrate: [100, 50, 100],
      data: data.data || {} // contains linkPath e.g., /post/post123
    };

    event.waitUntil(
      self.registration.showNotification(title, options)
    );
  } catch (err) {
    console.error('Error handling push event:', err);
  }
});

// Handle notification clicks (direct routing to threads)
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  
  const linkPath = event.notification.data?.linkPath || '/';
  
  // Dynamically resolve base subdirectory of sw.js to support hosting on GitHub Pages subfolders
  const basePath = self.location.pathname.replace('sw.js', '');
  const targetUrl = new URL(`${basePath}#${linkPath}`, self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList: any[]) => {
      // 1. If we have an open tab at this exact URL, focus it
      for (const client of clientList) {
        if (client.url === targetUrl && 'focus' in client) {
          return client.focus();
        }
      }
      
      // 2. If we have any open tab of our app, navigate it and focus
      for (const client of clientList) {
        if ('navigate' in client && 'focus' in client) {
          client.focus();
          return client.navigate(targetUrl);
        }
      }

      // 3. Otherwise, open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl);
      }
    })
  );
});
